### PR TITLE
[qtdeclarative] Allow QtQuick2 parameters to be configured. Contributes to MER#1361

### PR DESCRIPTION
**Pull request by matthewvogt**

### CODE REVIEW

**Comment by amccarthy** [comment]
It seems kind of pointless to keep the QSettings object around for something that is only used during initialisation. Otherwise LGTM.

**Comment by matthewvogt** [comment]
True, but I don't want to have to read the settings multiple times at startup, since it involves probing a bunch of files.  If anyone extends this to parameterise more values, it becomes more important.

**Comment by jpetrell** [comment]
Cool! I wonder if we should also move Flickable flickDeceleration and maximumFlickVelocity from Silica to here as they are Qt Quick properties, and non-Silica third party Qt Quick applications would benefit from good defaults.

**Comment by jpetrell** [comment]
FlickThreshold and RetainGrabVelocity are pixel-based, so I guess should be scaled to be resolution independent. I'll ask design if they want to tune StartDragDistance, PressAndHoldDelay, FlickThreshold and RetainGrabVelocity values (modify ini files, restart app, repeat) to find optimal values for different devices.

**Comment by jpetrell** [comment]
One config file is a bit problematic in one aspect: time parameters are often platform-specific (PressAndHoldDelay, PressDelay), pixel-based parameters (velocities, decelerations) device/display-specific. I guess duplicating the values between device configurations is not a biggie.

**Comment by jpetrell** [comment]
MinimumFlickVelocity, FlickDeceleration, MaximumFlickVelocity and MultiFlickThreshold at least would make sense, but I wouldn't mind also adding also FlickOvershoot (not important for Sailfish as we don't do overshoot), MultiFlickRatio and MultiFlickMaxBoost just to be complete. But would be nice to get comment from others too.

**Comment by matthewvogt** [comment]
Updated to include most obvious parameterization candidates.

I don't think it is worth trying to make it changeable at runtime, it would necessarily involve some performance penalty.

**Comment by matthewvogt** [comment]
@jpetrell: Anything else that would be helpful?

**Comment by jpetrell** [comment]
Wow there are many. :) LGTM

**Comment by matthewvogt** [comment]
Updated to restrict the settings lookup to the system directories, which prevents loading malicious configuration settings from the user directory.

**Pull request merged**
