### PR TITLE
[qtdeclarative] Create documentation packages. Fixes MER#1181 

### PR DESCRIPTION
**Pull request by blammit**

### CODE REVIEW

**Comment by martinjones** [comment]
LGTM

**Comment by blammit** [comment]
Anybody able to merge this and tag please?

**Comment by rburchell** [comment]
I wonder if it would make sense to build this at release level only, since I'm pretty sure it adds a good chunk onto build time. Did you do any measurement of how long it takes?

**Comment by blammit** [comment]
I don't have the measurements, but it does add a bit of time. I agree it makes sense to build it at release level only since the docs are unlikely to change from upstream. 

What's required to build it at release level? Is this sufficient? https://github.com/mer-qt/qtdeclarative/pull/75

**Comment by blammit** [comment]
Declined in favour of #75

**Pull request closed without merging**
